### ISSUE TITLE
App crashes with the recent JHU data update

### ISSUE THREAD

**Issue by anilbey** [dsbb-finddx/FIND_Cov_19_Tracker#28]
If I checkout the develop branch and run the app it gives this error.

```
  87: safeLabel
  80: addPolygons
  79: function_list[[i]]
  78: freduce
  77: _fseq
  76: eval
  75: eval
  73: %>%
  72: observeEventHandler [/Users/tuncel/git_repositories/FIND_Cov_19_Tracker/server.R#428]
   1: runApp
```

When I comment out this line below and revert the changes on `coronavirus.csv`, it works.
https://github.com/dsbb-finddx/FIND_Cov_19_Tracker/blob/f91497e5c59401be1d5b354dff58ca28df1adaff/cv_data.R#L12

One of the recent lines in the `coronavirus.csv` must be causing it.

When I only add these two new lines from `coronavirus.csv` back, it crashes again.
```
"Yemen","2020-04-14",84,1,0,0,0,"Yemen",NA
"US","2020-04-15",85,636350,28680,28326,2494,"USA",NA
```

**Comment by dsbb-finddx** [comment]
Yes, it is true. This happens with the previous version of the develop branch too.
Will look into it, thanks Anil!

**Comment by dsbb-finddx** [comment]
This is now fixed
